### ISSUE TITLE
Notifications can't be dismissed

### ISSUE THREAD

**Issue by edwloef** [modrinth/labrinth#214]
Issue:
When I try to dismiss a notification of a mod being updated, the loading bar goes to the end of the screen and just stops. Upon reload the notification is still there.

1. Go to the notifications window
2. Try to delete a notification

Expected behavior:
The loading bar goes to the end of the screen and the notification disappears.

Context:
I am using Firefox on Windows 10

**Comment by wafflecoffee** [comment]
Duplicate of modrinth/knossos#263. This is a frontend issue, not a backend one. It appears to be caused by [`566833d`](https://github.com/modrinth/knossos/commit/566833da6eb6cf2fa2970556bb11f690889d26de), so if you wish to dismiss notifications, I've reverted that commit on my own branch at https://emma-knossos.vercel.app (but this is not a permanent fix; modrinth/knossos#178 is unfixed on this branch)

**Comment by edwloef** [comment]
Ah, sorry, I wasn't aware.
