### ISSUE TITLE
Indexing over ~200,000 mods from curseforge grants a PayloadTooLarge Error

### ISSUE THREAD

**Issue by Geometrically** [modrinth/labrinth#35]
As the title says, when the `index_curseforge` function is passed with indices greater than about 200,000, the web server will panic and crash. I'm not sure how to increase the payload size with reqwest, but that seems like a viable solution unless we split up the payloads which is more complicated with no benifit (unless reqwest doesn't allow you to increase payload size)

**Comment by Aeledfyr** [comment]
A workaround that I have used for this is to run meilisearch with `--http-payload-size-limit 20971520` (set the limit to 20MiB instead of 10MiB), which should work as a temporary fix.  The proper way of fixing this would be to somehow batch the mods passed to meilisearch so that less data is sent per request.
