### ISSUE TITLE
Download counter not working after changing the version number

### ISSUE THREAD

**Issue by tr7zw** [modrinth/labrinth#351]
**Describe the bug**
After changing a file's version, the download counter will stop working. This happened to all files [here](https://modrinth.com/mod/3dskinlayers/versions) uploaded on the 4th of May, making them stuck at 0.

**To Reproduce**
1. Upload a new file
2. Change the version and save
3. File is unable to get downloads

**Additional context**
This was discussed in the discord and attempts were made to fix it, but so far the issue persists. The 1.17 files that I've uploaded later with the correct version initially work correctly.

**Comment by Zetvue** [comment]
Nuking the file didn't work either.
Somehow, it doesn't work for anything that uses the forge mod loader.. for some reason

**Comment by wafflecoffee** [comment]
The source of this issue was fixed in ac3a17b1784d41d345a45afd1a743fa9dcda2f31. Therefore, any files uploaded prior to August 17th, 2022 where the version number has been edited will be affected by this issue and will have a broken download counter. Note that this is a per-file issue, not a per-version issue.
