### ISSUE TITLE
Upload Bungeecord plugin but failed with error

### ISSUE THREAD

**Issue by wifi-left** [modrinth/labrinth#687]
### Describe the bug

Upload Bungeecord plugin but failed with error 'No plugin.yml found in the file'

But in fact, Bungeecord plugin didn't has 'plugin.yml' in the jar file. It only has 'bungee.yml'.

And for Velocity plugins, it only has 'velocity-plugin.json'

### Steps to reproduce

Add new project

Upload a Bungeecord or Velocity plugin.

Get the error.

### Expected behavior

Upload successfully.

### Additional context

I don't know if it's a UI problem or an API problem
So I posted the same issue at https://github.com/modrinth/knossos/issues/1299

**Comment by mopsy14** [comment]
Can confirm this.
And I might add this from [the official wiki of Bungeecord](https://www.spigotmc.org/wiki/create-your-first-bungeecord-plugin-proxy-spigotmc/):


Now we can create the plugin.yml file, so that BungeeCord recognizes that this is a plugin and tell it how to load it. Right click resources, and create a new file called plugin.yml.
You can also create a bungee.yml file if plugin.yml is already loaded by Bukkit.
