### ISSUE TITLE
Join date resets when you reset your password

### ISSUE THREAD

**Issue by averwhy** [modrinth/labrinth#889]
### Describe the bug

I joined modrinth previously (1-2 months ago) and just logged back in, however I forgot my password so naturally i reset it. However when I returned to my profile, I noticed that it says "Joined 1 minute ago" which isn't true. It seems that the join date got reset when I reset my password. Unsure if this is intentional or not so I thought to make the issue anyway

### Steps to reproduce

1. Have a preexisting Modrinth account
2. Reset password
3. Goto profile
4. Observe fresh join date

### Expected behavior

The join date remains the same

**Comment by averwhy** [comment]
![image](https://github.com/modrinth/labrinth/assets/43783082/4171ac48-277d-4596-b9a6-04cd2d774eb8)

**Comment by brawaru** [comment]
You have used an authenticator provider to sign in, and this automatically created a new account for you as seen by the presence of 1 at the end of your username. Your original account can be found at https://modrinth.com/user/averwhy. You can try to regain access to it by entering your username (averwhy) instead of an email in the password reset form.
