### ISSUE TITLE
Add a route for fetching contents of a collection. 

### ISSUE THREAD

**Issue by PouekDEV** [modrinth/labrinth#931]
### Is your suggested enhancement related to a problem? Please describe.

I wanted to make a program that fetches all mods in a collection and checks if they are available for the newest minecraft version. Looking through the documentation, I found nothing related to getting info from collections. Checking the GitHub issues, I have not found any requests for this either.

### Describe the solution you'd like

I would like to have a route in the API for fetching the contents of a collection. It would return a list containing the name of the mods, ids, and icons and would require the collection id for example `/v2/collection/lvHexa4f`.

**Comment by xXNickznXx** [comment]
@PouekDEV
There is no documentation on this as its still in development, but you can already use the `v3` api.

So you must do that on `v3` instead of `v2`.

You can see the endpoints here: [routes/v3/collections.rs#L31-L35](https://github.com/modrinth/labrinth/blob/master/src/routes/v3/collections.rs#L31-L35)

**Comment by PouekDEV** [comment]
Oh, that's very nice!
Thanks for the info.
